<div class="toolbar table-search" id="<?php echo $this->gridId; ?>_singlesearch">
    <div class="input-group">
        <input type="text" name="<?php echo $this->gridId; ?>_singlesearch_query" id="<?php echo $this->gridId; ?>_singlesearch_query" class="form-control">
        <span class="input-group-btn">
            <button type="button" name="" class="btn btn-primary" id="<?php echo $this->gridId; ?>_singlesearch_btn">
                <i class="icon-search"></i>
            </button>
        </span><!-- /.input-group-btn -->
    </div><!-- /.input-group -->
</div>